### PR TITLE
Design gift startpage

### PR DESCRIPTION
**Pull request by nilsishome**
## Description
- A section has been implemented with a design that was described in Figma and PBI.
- All text is only temporary
- Please comment if you have any suggestions or opinions about the design.

## Features
- The button's background color turns red on hover, in **desktop view**
- The button's background color turns red on click, in both **desktop** and **mobile view**

## Testing
This PBI only contained styling, and I found no page-breaking bugs in localhost.

## Changes made (in images)
**Desktop view:**

Screenshot 2024-12-29 at 17 51 01

**Mobile view:**

Screenshot 2024-12-29 at 17 51 17

### CODE REVIEW

**Review by El-Duckster — CHANGES_REQUESTED** [review]
Awesome job on the design! To keep things clean and avoid any style cascading, try adding unique class names or IDs to elements like button, p, h2, and img. It’ll help scope your styles better, prevent potintial conflicts, and make your code easier to manage.

**Review by Tobias-hubs — APPROVED** [review]
Looking good, 
Very pleasing design. 
Happy new year!

**Review by El-Duckster — APPROVED** [review]
perfect! Have a great start of a new year!

**Comment by nilsishome** [comment]
Thank you for your reviews! Happy new year to both of you :)

**Pull request merged**
